version: "3.5"

services:
  school-guardian-frontend:
    container_name: school-guardian-frontend
    image: gabrielsoaresdev/school-guardian-frontend:latest
    ports:
      - "3336:3336"
    restart: always
    networks:
      - proxy-reverse-network
      - school-guardian-network
networks:
  school-guardian-network:
    name: school-guardian-network
    external: true
  proxy-reverse-network:
    name: proxy-reverse-network
    external: true
