version: "3.5"

services:
  plagiarism-platform-frontend:
    container_name: plagiarism-platform-frontend
    image: gabrielsoaresdev/default-project-nextjs:latest
    ports:
      - "3336:3336"
    restart: always
    networks:
      - proxy-reverse-network
      - plagiarism-platform-network
networks:
  plagiarism-platform-network:
    name: plagiarism-platform-network
    external: true
  proxy-reverse-network:
    name: proxy-reverse-network
    external: true
