version: "3.5"

services:
   school-guardian-frontend:
    container_name: school-guardian-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3336:3336
    volumes:
      - .:/app/school-guardian-frontend
      - /app/school-guardian-frontend/node_modules
      - /app/school-guardian-frontend/.next
    networks:
      - school-guardian-frontend-network
networks:
  school-guardian-frontend-network:
    name: school-guardian-frontend-network
    external: true
