version: "3.5"

services:
  plagiarism-platform-frontend:
    container_name: plagiarism-platform-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3336:3336
    volumes:
      - .:/app/plagiarism-platform-frontend
      - /app/plagiarism-platform-frontend/node_modules
      - /app/plagiarism-platform-frontend/.next
    networks:
      - plagiarism-platform-network
networks:
  plagiarism-platform-network:
    name: plagiarism-platform-network
    external: true
